FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./etl/pyproject.toml /app/pyproject.toml
RUN pip install --no-cache-dir \
    faker>=37.12.0 \
    psycopg2-binary>=2.9.9

COPY ./etl/src/upi_events_live_mutations.py /app/upi_events_live_mutations.py

CMD ["python", "/app/upi_events_live_mutations.py"]
